import uuid
from django.conf import settings
from django.db import models

def notification_number(): return f"NOT-{uuid.uuid4().hex[:10].upper()}"
class Notification(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); notification_number=models.CharField(max_length=30,unique=True,default=notification_number,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="notifications"); household=models.ForeignKey("households.Household",null=True,blank=True,on_delete=models.SET_NULL,related_name="notifications"); recipient=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="notifications"); sender=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,on_delete=models.SET_NULL,related_name="sent_notifications"); title=models.CharField(max_length=200); message=models.TextField(); notification_type=models.CharField(max_length=20); priority=models.CharField(max_length=10,default="medium"); reference_type=models.CharField(max_length=40,blank=True); reference_id=models.UUIDField(null=True,blank=True); is_read=models.BooleanField(default=False,db_index=True); read_at=models.DateTimeField(null=True,blank=True); status=models.CharField(max_length=20,default="active"); created_at=models.DateTimeField(auto_now_add=True)
 class Meta: db_table="notifications_notification"; ordering=["-created_at"]; indexes=[models.Index(fields=["recipient","is_read","-created_at"]),models.Index(fields=["family","notification_type"])]
class NotificationPreference(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="notification_preference"); in_app_enabled=models.BooleanField(default=True); email_enabled=models.BooleanField(default=False); push_enabled=models.BooleanField(default=False); muted_types=models.JSONField(default=list,blank=True); updated_at=models.DateTimeField(auto_now=True)
 class Meta: db_table="notifications_preference"
class Announcement(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="announcements"); title=models.CharField(max_length=200); description=models.TextField(); attachment=models.FileField(upload_to="announcements/",null=True,blank=True); visibility=models.CharField(max_length=20,default="family"); start_date=models.DateTimeField(); end_date=models.DateTimeField(null=True,blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="announcements_created"); created_at=models.DateTimeField(auto_now_add=True)
 class Meta: db_table="notifications_announcement"; ordering=["-created_at"]
class ActivityTimeline(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="activity_timeline"); household=models.ForeignKey("households.Household",null=True,blank=True,on_delete=models.SET_NULL); member=models.ForeignKey("members.Member",null=True,blank=True,on_delete=models.SET_NULL,related_name="timeline_events"); module=models.CharField(max_length=40); action=models.CharField(max_length=60); reference_type=models.CharField(max_length=40,blank=True); reference_id=models.UUIDField(null=True,blank=True); description=models.TextField(); icon=models.CharField(max_length=50,blank=True); created_at=models.DateTimeField(auto_now_add=True)
 class Meta: db_table="notifications_activity_timeline"; ordering=["-created_at"]; indexes=[models.Index(fields=["family","module","-created_at"])]
class LoginHistory(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); member=models.ForeignKey("members.Member",on_delete=models.CASCADE,related_name="login_history"); login_time=models.DateTimeField(auto_now_add=True); logout_time=models.DateTimeField(null=True,blank=True); ip_address=models.GenericIPAddressField(null=True,blank=True); browser=models.CharField(max_length=255,blank=True); device=models.CharField(max_length=255,blank=True); operating_system=models.CharField(max_length=100,blank=True); status=models.CharField(max_length=20,default="success")
 class Meta: db_table="notifications_login_history"; ordering=["-login_time"]
class SecurityEvent(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); member=models.ForeignKey("members.Member",null=True,blank=True,on_delete=models.SET_NULL,related_name="security_events"); event_type=models.CharField(max_length=40); severity=models.CharField(max_length=10,default="medium"); description=models.TextField(); ip_address=models.GenericIPAddressField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
 class Meta: db_table="notifications_security_event"; ordering=["-created_at"]
