# Generated by Django 5.1.4 on 2026-07-13 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="head_of_household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_households",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="households_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="household",
            index=models.Index(fields=["family", "status"], name="households__family__eff7ca_idx"),
        ),
        migrations.AddConstraint(
            model_name="household",
            constraint=models.UniqueConstraint(
                fields=("family", "household_code"), name="unique_household_code_per_family"
            ),
        ),
    ]
