import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations,models
class Migration(migrations.Migration):
 initial=True
 dependencies=[("families","0001_initial"),("households","0001_initial"),("members","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
 migrations.CreateModel(name="Notification",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("notification_number",models.CharField(max_length=30,unique=True)),("title",models.CharField(max_length=200)),("message",models.TextField()),("notification_type",models.CharField(max_length=20)),("priority",models.CharField(default="medium",max_length=10)),("reference_type",models.CharField(blank=True,max_length=40)),("reference_id",models.UUIDField(blank=True,null=True)),("is_read",models.BooleanField(db_index=True,default=False)),("read_at",models.DateTimeField(blank=True,null=True)),("status",models.CharField(default="active",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to="families.family")),("household",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="notifications",to="households.household")),("recipient",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to=settings.AUTH_USER_MODEL)),("sender",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="sent_notifications",to=settings.AUTH_USER_MODEL))],options={"db_table":"notifications_notification","ordering":["-created_at"]}),
 migrations.CreateModel(name="NotificationPreference",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("in_app_enabled",models.BooleanField(default=True)),("email_enabled",models.BooleanField(default=False)),("push_enabled",models.BooleanField(default=False)),("muted_types",models.JSONField(blank=True,default=list)),("updated_at",models.DateTimeField(auto_now=True)),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="notification_preference",to=settings.AUTH_USER_MODEL))],options={"db_table":"notifications_preference"}),
 migrations.CreateModel(name="Announcement",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("title",models.CharField(max_length=200)),("description",models.TextField()),("attachment",models.FileField(blank=True,null=True,upload_to="announcements/")),("visibility",models.CharField(default="family",max_length=20)),("start_date",models.DateTimeField()),("end_date",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="announcements_created",to=settings.AUTH_USER_MODEL)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="announcements",to="families.family"))],options={"db_table":"notifications_announcement"}),
 migrations.CreateModel(name="ActivityTimeline",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("module",models.CharField(max_length=40)),("action",models.CharField(max_length=60)),("reference_type",models.CharField(blank=True,max_length=40)),("reference_id",models.UUIDField(blank=True,null=True)),("description",models.TextField()),("icon",models.CharField(blank=True,max_length=50)),("created_at",models.DateTimeField(auto_now_add=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="activity_timeline",to="families.family")),("household",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="households.household")),("member",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="timeline_events",to="members.member"))],options={"db_table":"notifications_activity_timeline","ordering":["-created_at"]}),
 migrations.CreateModel(name="LoginHistory",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("login_time",models.DateTimeField(auto_now_add=True)),("logout_time",models.DateTimeField(blank=True,null=True)),("ip_address",models.GenericIPAddressField(blank=True,null=True)),("browser",models.CharField(blank=True,max_length=255)),("device",models.CharField(blank=True,max_length=255)),("operating_system",models.CharField(blank=True,max_length=100)),("status",models.CharField(default="success",max_length=20)),("member",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="login_history",to="members.member"))],options={"db_table":"notifications_login_history","ordering":["-login_time"]}),
 migrations.CreateModel(name="SecurityEvent",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("event_type",models.CharField(max_length=40)),("severity",models.CharField(default="medium",max_length=10)),("description",models.TextField()),("ip_address",models.GenericIPAddressField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("member",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="security_events",to="members.member"))],options={"db_table":"notifications_security_event","ordering":["-created_at"]}),
 migrations.AddIndex(model_name="notification",index=models.Index(fields=["recipient","is_read","-created_at"],name="notificatio_recipie_6850ba_idx")),migrations.AddIndex(model_name="activitytimeline",index=models.Index(fields=["family","module","-created_at"],name="notificatio_family__0df3ee_idx"))]
