# Generated by Django 5.1.4 on 2026-09-22 13:44

from django.conf import settings
from django.db import migrations, models

import apps.notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0001_initial"),
        ("households", "0002_initial"),
        ("notifications", "0002_family_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="activitytimeline",
            new_name="notificatio_family__42fb1a_idx",
            old_name="notificatio_family__0df3ee_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_684eac_idx",
            old_name="notificatio_recipie_6850ba_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_number",
            field=models.CharField(
                default=apps.notifications.models.notification_number,
                editable=False,
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["family", "notification_type"], name="notificatio_family__07d3a8_idx"
            ),
        ),
    ]
