# Generated by Django 5.1.4 on 2026-09-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="analyticscache",
            new_name="dashboard_a_family__caa209_idx",
            old_name="dashboard_a_family__d903fb_idx",
        ),
    ]
