# Initial schema; generated as a compact migration due to unavailable local Django dependencies.
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations,models
class Migration(migrations.Migration):
 initial=True
 dependencies=[("families","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
 migrations.CreateModel(name="SystemSetting",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("key",models.CharField(max_length=100)),("value",models.JSONField(default=dict)),("module",models.CharField(default="general",max_length=40)),("updated_at",models.DateTimeField(auto_now=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="system_settings",to="families.family")),("updated_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={"db_table":"administration_system_setting"}),
 migrations.CreateModel(name="FeatureFlag",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("key",models.CharField(max_length=60)),("enabled",models.BooleanField(default=True)),("description",models.TextField(blank=True)),("updated_at",models.DateTimeField(auto_now=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="feature_flags",to="families.family")),("updated_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={"db_table":"administration_feature_flag"}),
 migrations.CreateModel(name="ApplicationConfiguration",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("email_config",models.JSONField(blank=True,default=dict)),("sms_config",models.JSONField(blank=True,default=dict)),("storage_provider",models.CharField(default="local",max_length=30)),("cache_provider",models.CharField(default="redis",max_length=30)),("logging_level",models.CharField(default="INFO",max_length=20)),("maintenance_mode",models.BooleanField(default=False)),("maintenance_message",models.TextField(blank=True)),("allowed_users",models.JSONField(blank=True,default=list)),("updated_at",models.DateTimeField(auto_now=True)),("family",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="application_configuration",to="families.family")),("updated_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={"db_table":"administration_configuration"}),
 migrations.CreateModel(name="Lookup",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("lookup_type",models.CharField(max_length=40)),("name",models.CharField(max_length=100)),("code",models.CharField(blank=True,max_length=40)),("status",models.CharField(default="active",max_length=20)),("sort_order",models.PositiveIntegerField(default=0)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="administration_lookups",to="families.family"))],options={"db_table":"administration_lookup"}),
 migrations.CreateModel(name="FinancialYear",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("name",models.CharField(max_length=30)),("start_date",models.DateField()),("end_date",models.DateField()),("is_current",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="financial_years",to="families.family"))],options={"db_table":"administration_financial_year"}),
 migrations.CreateModel(name="BackupHistory",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("backup_type",models.CharField(max_length=30)),("status",models.CharField(default="queued",max_length=20)),("storage_path",models.CharField(blank=True,max_length=500)),("checksum",models.CharField(blank=True,max_length=64)),("created_at",models.DateTimeField(auto_now_add=True)),("completed_at",models.DateTimeField(blank=True,null=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="backup_history",to="families.family")),("created_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={"db_table":"administration_backup_history"}),
 migrations.CreateModel(name="RestoreHistory",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("restore_type",models.CharField(max_length=30)),("status",models.CharField(default="queued",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("completed_at",models.DateTimeField(blank=True,null=True)),("details",models.JSONField(blank=True,default=dict)),("backup",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="administration.backuphistory")),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="restore_history",to="families.family")),("performed_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={"db_table":"administration_restore_history"}),
 migrations.AddConstraint(model_name="systemsetting",constraint=models.UniqueConstraint(fields=("family","key"),name="system_setting_per_family")),migrations.AddConstraint(model_name="featureflag",constraint=models.UniqueConstraint(fields=("family","key"),name="feature_flag_per_family")),migrations.AddConstraint(model_name="lookup",constraint=models.UniqueConstraint(fields=("family","lookup_type","name"),name="administration_lookup_unique")),migrations.AddConstraint(model_name="financialyear",constraint=models.UniqueConstraint(fields=("family","name"),name="financial_year_per_family"))]
