# Generated by Django 5.1.4 on 2026-09-22 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backuphistory",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="restorehistory",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="lookup",
            index=models.Index(
                fields=["family", "lookup_type", "status"], name="administrat_family__e6f93a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemsetting",
            index=models.Index(fields=["family", "module"], name="administrat_family__521ea9_idx"),
        ),
    ]
