# Generated by Django 5.1.4 on 2026-07-14 02:39

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.expenses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
        ("households", "0002_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="lucide-react icon name", max_length=50),
                ),
                (
                    "color",
                    models.CharField(
                        default="#64748b", help_text="Hex color, e.g. #64748b", max_length=7
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="families.family",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expense Categories",
                "db_table": "expenses_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "expense_number",
                    models.CharField(
                        default=apps.expenses.models.generate_expense_number,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("expense_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("wallet", "Wallet"),
                            ("cheque", "Cheque"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("household", "Household"),
                            ("family", "Entire Family"),
                        ],
                        default="household",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("settled", "Settled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="families.family",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="households.household",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses_paid",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="expenses.expensecategory",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_expense",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="expenses.expense",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_comments",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "share_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "share_percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "settled_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "pending_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partially_settled", "Partially Settled"),
                            ("settled", "Settled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="expenses.expense",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_shares",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_participant",
            },
        ),
        migrations.CreateModel(
            name="ExpenseSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "received_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("settlement_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("recorded", "Recorded"), ("reversed", "Reversed")],
                        default="recorded",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="expenses.expense",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_settlements",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_settlement",
                "ordering": ["-settlement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerPostingQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("expense_created", "Expense Created"),
                            ("expense_updated", "Expense Updated"),
                            ("expense_cancelled", "Expense Cancelled"),
                            ("settlement_recorded", "Settlement Recorded"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("posted", "Posted")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_postings",
                        to="expenses.expense",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_ledger_posting_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to=apps.expenses.models.attachment_upload_path)),
                ("file_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "checksum",
                    models.CharField(
                        blank=True, help_text="SHA-256 of the file content", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="expenses.expense",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expenses_attachment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["expense"], name="expenses_at_expense_a4db2a_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(fields=["family", "status"], name="expenses_ca_family__94bc0e_idx"),
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                fields=("family", "name"), name="unique_category_name_per_family"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["family", "status"], name="expenses_ex_family__4d1707_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["household"], name="expenses_ex_househo_4ff49e_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["paid_by"], name="expenses_ex_paid_by_a99d03_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["category"], name="expenses_ex_categor_20264a_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["expense_date"], name="expenses_ex_expense_cf8a73_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["expense_number"], name="expenses_ex_expense_2fef2f_idx"),
        ),
        migrations.AddIndex(
            model_name="expensecomment",
            index=models.Index(
                fields=["expense", "created_at"], name="expenses_co_expense_9d451a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenseparticipant",
            index=models.Index(fields=["expense", "status"], name="expenses_pa_expense_dda6b9_idx"),
        ),
        migrations.AddIndex(
            model_name="expenseparticipant",
            index=models.Index(fields=["member"], name="expenses_pa_member__222a01_idx"),
        ),
        migrations.AddConstraint(
            model_name="expenseparticipant",
            constraint=models.UniqueConstraint(
                fields=("expense", "member"), name="unique_participant_per_expense"
            ),
        ),
        migrations.AddIndex(
            model_name="expensesettlement",
            index=models.Index(fields=["expense", "member"], name="expenses_se_expense_540ba8_idx"),
        ),
        migrations.AddIndex(
            model_name="expensesettlement",
            index=models.Index(fields=["status"], name="expenses_se_status_4f03f8_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerpostingqueue",
            index=models.Index(fields=["family", "status"], name="expenses_le_family__b014d3_idx"),
        ),
    ]
