# Generated by Django 5.1.4 on 2026-07-13 03:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("logout_all", "Logout All Devices"),
                            ("password_changed", "Password Changed"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("password_reset_completed", "Password Reset Completed"),
                            ("profile_updated", "Profile Updated"),
                            ("avatar_updated", "Avatar Updated"),
                            ("member_deactivated", "Member Deactivated"),
                            ("member_reactivated", "Member Reactivated"),
                            ("member_password_reset", "Member Password Reset by Admin"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("family_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who performed the action. Null for unauthenticated events (e.g. failed login).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "action", "-created_at"],
                        name="audit_log_actor_i_da5b28_idx",
                    )
                ],
            },
        ),
    ]
