# Generated by Django 5.1.4 on 2026-07-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("logout_all", "Logout All Devices"),
                    ("password_changed", "Password Changed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("profile_updated", "Profile Updated"),
                    ("avatar_updated", "Avatar Updated"),
                    ("member_deactivated", "Member Deactivated"),
                    ("member_reactivated", "Member Reactivated"),
                    ("member_password_reset", "Member Password Reset by Admin"),
                    ("family_created", "Family Created"),
                    ("family_updated", "Family Updated"),
                    ("household_created", "Household Created"),
                    ("household_updated", "Household Updated"),
                    ("household_deactivated", "Household Deactivated"),
                    ("household_head_changed", "Household Head Changed"),
                    ("member_profile_created", "Member Profile Created"),
                    ("member_profile_updated", "Member Profile Updated"),
                    ("member_transferred", "Member Transferred"),
                    ("invitation_sent", "Invitation Sent"),
                    ("invitation_accepted", "Invitation Accepted"),
                    ("invitation_rejected", "Invitation Rejected"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
