# Generated by Django 5.1.4 on 2026-07-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("logout_all", "Logout All Devices"),
                    ("password_changed", "Password Changed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("profile_updated", "Profile Updated"),
                    ("avatar_updated", "Avatar Updated"),
                    ("member_deactivated", "Member Deactivated"),
                    ("member_reactivated", "Member Reactivated"),
                    ("member_password_reset", "Member Password Reset by Admin"),
                    ("family_created", "Family Created"),
                    ("family_updated", "Family Updated"),
                    ("household_created", "Household Created"),
                    ("household_updated", "Household Updated"),
                    ("household_deactivated", "Household Deactivated"),
                    ("household_head_changed", "Household Head Changed"),
                    ("member_profile_created", "Member Profile Created"),
                    ("member_profile_updated", "Member Profile Updated"),
                    ("member_transferred", "Member Transferred"),
                    ("invitation_sent", "Invitation Sent"),
                    ("invitation_accepted", "Invitation Accepted"),
                    ("invitation_rejected", "Invitation Rejected"),
                    ("expense_created", "Expense Created"),
                    ("expense_updated", "Expense Updated"),
                    ("expense_cancelled", "Expense Cancelled"),
                    ("expense_restored", "Expense Restored"),
                    ("expense_category_created", "Expense Category Created"),
                    ("expense_category_updated", "Expense Category Updated"),
                    ("expense_settlement_recorded", "Expense Settlement Recorded"),
                    ("expense_attachment_uploaded", "Expense Attachment Uploaded"),
                    ("expense_attachment_downloaded", "Expense Attachment Downloaded"),
                    ("loan_created", "Loan Created"),
                    ("loan_updated", "Loan Updated"),
                    ("loan_cancelled", "Loan Cancelled"),
                    ("loan_restored", "Loan Restored"),
                    ("loan_payment_added", "Loan Payment Added"),
                    ("loan_reminder_created", "Loan Reminder Created"),
                    ("loan_reminder_dismissed", "Loan Reminder Dismissed"),
                    ("loan_document_uploaded", "Loan Document Uploaded"),
                    ("borrow_created", "Borrow Transaction Created"),
                    ("lend_created", "Lend Transaction Created"),
                    ("borrow_lend_settlement_recorded", "Borrow/Lend Settlement Recorded"),
                    ("ledger_account_created", "Ledger Account Created"),
                    ("ledger_journal_created", "Journal Created"),
                    ("ledger_journal_posted", "Journal Posted"),
                    ("ledger_adjustment_created", "Adjustment Entry Created"),
                    ("ledger_statement_exported", "Statement Exported"),
                    ("ledger_balance_updated", "Account Balance Updated"),
                    ("ledger_period_closed", "Financial Period Closed"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
