# Generated by Django 5.1.4 on 2026-09-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_auditfieldchange"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditfieldchange",
            new_name="audit_field_audit_l_181d3b_idx",
            old_name="audit_field_audit_l_1ee033_idx",
        ),
    ]
