# Generated by Django 5.1.4 on 2026-07-15 18:57

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.borrow_lend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
        ("households", "0002_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        default=apps.borrow_lend.models.generate_borrow_number,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("external_lender_name", models.CharField(blank=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("wallet", "Wallet"),
                            ("cheque", "Cheque"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partially_settled", "Partially Settled"),
                            ("settled", "Settled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "settled_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amounts_borrowed",
                        to="members.member",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrow_transactions",
                        to="families.family",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrow_transactions",
                        to="households.household",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amounts_lent_to_others",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "borrow_lend_borrow_transaction",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["family", "status"], name="borrow_lend_family__b6b445_idx"
                    ),
                    models.Index(fields=["borrower"], name="borrow_lend_borrowe_a2ba9b_idx"),
                    models.Index(fields=["household"], name="borrow_lend_househo_228bc0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LendTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        default=apps.borrow_lend.models.generate_lend_number,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("external_receiver_name", models.CharField(blank=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("wallet", "Wallet"),
                            ("cheque", "Cheque"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partially_settled", "Partially Settled"),
                            ("settled", "Settled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "settled_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lend_transactions",
                        to="families.family",
                    ),
                ),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amounts_given",
                        to="members.member",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lend_transactions",
                        to="households.household",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amounts_received",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "borrow_lend_lend_transaction",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["family", "status"], name="borrow_lend_family__ddf087_idx"
                    ),
                    models.Index(fields=["giver"], name="borrow_lend_giver_i_523011_idx"),
                    models.Index(fields=["household"], name="borrow_lend_househo_156665_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[("borrow", "Borrow Transaction"), ("lend", "Lend Transaction")],
                        max_length=20,
                    ),
                ),
                ("reference_id", models.UUIDField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "settled_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cumulative total settled after this event",
                        max_digits=12,
                    ),
                ),
                ("remaining_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("recorded", "Recorded"), ("reversed", "Reversed")],
                        default="recorded",
                        max_length=20,
                    ),
                ),
                ("settlement_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements_made",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "borrow_lend_settlement",
                "ordering": ["-settlement_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="borrow_lend_referen_78607b_idx",
                    )
                ],
            },
        ),
    ]
