# Generated by Django 5.1.4 on 2026-09-22 12:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[("free", "Free"), ("family", "Family"), ("premium", "Premium")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("price_inr_paise", models.PositiveIntegerField(default=0)),
                ("price_usd_cents", models.PositiveIntegerField(default=0)),
                ("member_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("household_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("monthly_expense_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("storage_mb", models.PositiveIntegerField(default=50)),
                ("ai_enabled", models.BooleanField(default=False)),
                ("stripe_price_id", models.CharField(blank=True, max_length=80)),
                ("razorpay_plan_id", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "db_table": "billing_plan",
                "ordering": ["price_inr_paise"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("stripe", "Stripe"),
                            ("razorpay", "Razorpay"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_session_id", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(default="open", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkouts",
                        to="families.family",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="billing.plan"
                    ),
                ),
            ],
            options={
                "db_table": "billing_checkout_session",
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("stripe", "Stripe"),
                            ("razorpay", "Razorpay"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_id", models.CharField(max_length=120, unique=True)),
                ("event_type", models.CharField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="processed", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_events",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "db_table": "billing_payment_event",
                "indexes": [
                    models.Index(
                        fields=["provider", "event_type"], name="billing_pay_provide_62108a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("stripe", "Stripe"),
                            ("razorpay", "Razorpay"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("provider_customer_id", models.CharField(blank=True, max_length=80)),
                ("provider_subscription_id", models.CharField(blank=True, max_length=80)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_subscription",
                        to="families.family",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscription",
                "indexes": [
                    models.Index(
                        fields=["status", "provider"], name="billing_sub_status_b8e69c_idx"
                    )
                ],
            },
        ),
    ]
