import uuid
from django.conf import settings
from django.db import models
class SystemSetting(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="system_settings"); key=models.CharField(max_length=100); value=models.JSONField(default=dict); module=models.CharField(max_length=40,default="general"); updated_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); updated_at=models.DateTimeField(auto_now=True)
 class Meta: db_table="administration_system_setting"; constraints=[models.UniqueConstraint(fields=["family","key"],name="system_setting_per_family")]; indexes=[models.Index(fields=["family","module"])]
class FeatureFlag(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="feature_flags"); key=models.CharField(max_length=60); enabled=models.BooleanField(default=True); description=models.TextField(blank=True); updated_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); updated_at=models.DateTimeField(auto_now=True)
 class Meta: db_table="administration_feature_flag"; constraints=[models.UniqueConstraint(fields=["family","key"],name="feature_flag_per_family")]
class ApplicationConfiguration(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.OneToOneField("families.Family",on_delete=models.CASCADE,related_name="application_configuration"); email_config=models.JSONField(default=dict,blank=True); sms_config=models.JSONField(default=dict,blank=True); storage_provider=models.CharField(max_length=30,default="local"); cache_provider=models.CharField(max_length=30,default="redis"); logging_level=models.CharField(max_length=20,default="INFO"); maintenance_mode=models.BooleanField(default=False); maintenance_message=models.TextField(blank=True); allowed_users=models.JSONField(default=list,blank=True); updated_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); updated_at=models.DateTimeField(auto_now=True)
 class Meta: db_table="administration_configuration"
class Lookup(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="administration_lookups"); lookup_type=models.CharField(max_length=40); name=models.CharField(max_length=100); code=models.CharField(max_length=40,blank=True); status=models.CharField(max_length=20,default="active"); sort_order=models.PositiveIntegerField(default=0); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
 class Meta: db_table="administration_lookup"; constraints=[models.UniqueConstraint(fields=["family","lookup_type","name"],name="administration_lookup_unique")]; indexes=[models.Index(fields=["family","lookup_type","status"])]
class FinancialYear(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="financial_years"); name=models.CharField(max_length=30); start_date=models.DateField(); end_date=models.DateField(); is_current=models.BooleanField(default=False); created_at=models.DateTimeField(auto_now_add=True)
 class Meta: db_table="administration_financial_year"; constraints=[models.UniqueConstraint(fields=["family","name"],name="financial_year_per_family")]
class BackupHistory(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="backup_history"); backup_type=models.CharField(max_length=30); status=models.CharField(max_length=20,default="queued"); storage_path=models.CharField(max_length=500,blank=True); checksum=models.CharField(max_length=64,blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); created_at=models.DateTimeField(auto_now_add=True); completed_at=models.DateTimeField(null=True,blank=True)
 class Meta: db_table="administration_backup_history"; ordering=["-created_at"]
class RestoreHistory(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); family=models.ForeignKey("families.Family",on_delete=models.CASCADE,related_name="restore_history"); restore_type=models.CharField(max_length=30); status=models.CharField(max_length=20,default="queued"); backup=models.ForeignKey(BackupHistory,null=True,blank=True,on_delete=models.SET_NULL); performed_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); created_at=models.DateTimeField(auto_now_add=True); completed_at=models.DateTimeField(null=True,blank=True); details=models.JSONField(default=dict,blank=True)
 class Meta: db_table="administration_restore_history"; ordering=["-created_at"]
