# Generated by Django 5.1.4 on 2026-07-15 18:57

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.loans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
        ("households", "0002_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "loan_number",
                    models.CharField(
                        default=apps.loans.models.generate_loan_number,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "loan_source",
                    models.CharField(
                        choices=[
                            ("internal", "Internal (family member)"),
                            ("external", "External"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("external_lender_name", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Annual percentage rate",
                        max_digits=5,
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[("none", "None"), ("simple", "Simple"), ("compound", "Compound")],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("loan_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "allow_overpayment",
                    models.BooleanField(
                        default=False,
                        help_text="If off (default), a payment larger than the remaining balance is rejected.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans_borrowed",
                        to="members.member",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="families.family",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans",
                        to="households.household",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans_lent",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loans_loan",
                "ordering": ["-loan_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanInstallment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("installment_number", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "loans_installment",
                "ordering": ["installment_number"],
            },
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        default=apps.loans.models.generate_payment_number,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "interest_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "principal_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("wallet", "Wallet"),
                            ("cheque", "Cheque"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.loans.models.loan_payment_attachment_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="loans.loaninstallment",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "loans_payment",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_types",
                        to="families.family",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loans_type",
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loans",
                to="loans.loantype",
            ),
        ),
        migrations.CreateModel(
            name="InterestConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[("none", "None"), ("simple", "Simple"), ("compound", "Compound")],
                        default="simple",
                        max_length=20,
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=5),
                ),
                (
                    "compounding_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="annually",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_configurations",
                        to="families.family",
                    ),
                ),
                (
                    "loan_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interest_configurations",
                        to="loans.loantype",
                    ),
                ),
            ],
            options={
                "db_table": "loans_interest_configuration",
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("due_date", "Upcoming Due Date"),
                            ("overdue", "Overdue Loan"),
                            ("installment", "Pending Installment"),
                            ("custom", "Custom Reminder"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("remind_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_reminders",
                        to="families.family",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="loans.loaninstallment",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="loans.loan",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_reminders",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "db_table": "loans_reminder",
                "ordering": ["remind_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerPostingQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("loan_created", "Loan Created"),
                            ("loan_updated", "Loan Updated"),
                            ("loan_cancelled", "Loan Cancelled"),
                            ("loan_payment_recorded", "Loan Payment Recorded"),
                            ("borrow_entry", "Borrow Entry"),
                            ("lend_entry", "Lend Entry"),
                            ("settlement_recorded", "Settlement Recorded"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("posted", "Posted")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        help_text="e.g. Loan, BorrowTransaction, LendTransaction", max_length=50
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "db_table": "loans_ledger_posting_queue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["family", "status"], name="loans_ledge_family__437611_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="loaninstallment",
            index=models.Index(fields=["loan", "status"], name="loans_insta_loan_id_1d25e0_idx"),
        ),
        migrations.AddIndex(
            model_name="loaninstallment",
            index=models.Index(fields=["due_date"], name="loans_insta_due_dat_b3ea89_idx"),
        ),
        migrations.AddConstraint(
            model_name="loaninstallment",
            constraint=models.UniqueConstraint(
                fields=("loan", "installment_number"), name="unique_installment_number_per_loan"
            ),
        ),
        migrations.AddIndex(
            model_name="loanpayment",
            index=models.Index(
                fields=["loan", "-payment_date"], name="loans_payme_loan_id_a7d2e8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="loantype",
            constraint=models.UniqueConstraint(
                fields=("family", "name"), name="unique_loan_type_name_per_family"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["family", "status"], name="loans_loan_family__c76e4a_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["borrower"], name="loans_loan_borrowe_4ce53f_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["lender"], name="loans_loan_lender__e05194_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["household"], name="loans_loan_househo_c55553_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["loan_number"], name="loans_loan_loan_nu_9c0f1b_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["due_date"], name="loans_loan_due_dat_1042a5_idx"),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(fields=["family", "status"], name="loans_remin_family__f3d455_idx"),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(fields=["member", "status"], name="loans_remin_member__5ab7f8_idx"),
        ),
    ]
