# Generated by Django 5.1.4 on 2026-07-18 03:38

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.ledger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_groups",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_account_group",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "FY 2025-26" or "January 2026"', max_length=100
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_periods",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_financial_period",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ClosingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("closing_balances_snapshot", models.JSONField(default=dict)),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_periods",
                        to="families.family",
                    ),
                ),
                (
                    "financial_period",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_record",
                        to="ledger.financialperiod",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_closing_period",
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "journal_number",
                    models.CharField(
                        default=apps.ledger.models.generate_journal_number,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("expense", "Expense"),
                            ("expense_settlement", "Expense Settlement"),
                            ("income", "Income"),
                            ("loan_creation", "Loan Creation"),
                            ("loan_payment", "Loan Payment"),
                            ("borrow", "Borrow"),
                            ("lend", "Lend"),
                            ("adjustment", "Adjustment"),
                            ("opening_balance", "Opening Balance"),
                            ("manual_journal", "Manual Journal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, help_text="e.g. Expense, Loan, Settlement", max_length=50
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=64)),
                ("journal_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_journal",
                "ordering": ["-journal_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdjustmentEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_entries",
                        to="families.family",
                    ),
                ),
                (
                    "adjustment_journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_record",
                        to="ledger.journal",
                    ),
                ),
                (
                    "original_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments_against",
                        to="ledger.journal",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_adjustment_entry",
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("account_code", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_system_account",
                    models.BooleanField(
                        default=False,
                        help_text="Seeded default account (Cash, Bank, ...) — cannot be deleted.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="ledger.accountgroup",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_accounts",
                        to="families.family",
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_accounts",
                        to="ledger.ledgeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_account",
                "ordering": ["account_code"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ledger.journal",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="ledger.ledgeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_journal_entry",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "debit_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "credit_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="ledger.ledgeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_account_balance",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ledger_number",
                    models.CharField(
                        default=apps.ledger.models.generate_ledger_number,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("opening_balance", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("closing_balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="ledger.journal",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="ledger.ledgeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_entry",
                "ordering": ["transaction_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="families.family",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="ledger.financialperiod",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="ledger.ledgeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_opening_balance",
            },
        ),
        migrations.AddConstraint(
            model_name="accountgroup",
            constraint=models.UniqueConstraint(
                fields=("family", "name"), name="unique_account_group_per_family"
            ),
        ),
        migrations.AddIndex(
            model_name="financialperiod",
            index=models.Index(fields=["family", "status"], name="ledger_fina_family__144aeb_idx"),
        ),
        migrations.AddConstraint(
            model_name="financialperiod",
            constraint=models.UniqueConstraint(
                fields=("family", "name"), name="unique_period_name_per_family"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["family", "status"], name="ledger_jour_family__0e1df4_idx"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["transaction_type"], name="ledger_jour_transac_bbb04a_idx"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["reference_type", "reference_id"], name="ledger_jour_referen_8c9ec6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["journal_number"], name="ledger_jour_journal_279182_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(fields=["family", "status"], name="ledger_acco_family__af669f_idx"),
        ),
        migrations.AddConstraint(
            model_name="ledgeraccount",
            constraint=models.UniqueConstraint(
                fields=("family", "account_code"), name="unique_account_code_per_family"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["journal"], name="ledger_jour_journal_74fc0d_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["ledger_account"], name="ledger_jour_ledger__97c567_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["ledger_account", "transaction_date"], name="ledger_entr_ledger__66285a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["journal"], name="ledger_entr_journal_c4e536_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["ledger_number"], name="ledger_entr_ledger__d18083_idx"),
        ),
        migrations.AddConstraint(
            model_name="openingbalance",
            constraint=models.UniqueConstraint(
                fields=("ledger_account", "financial_period"),
                name="unique_opening_balance_per_period",
            ),
        ),
    ]
