import { Menu, Search, X } from "lucide-react";
import { useState } from "react";
import { Link, NavLink, Outlet } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { visibleNavigation } from "@/config/navigation";
import { APP_NAME } from "@/constants";
import { useLogout, useProfile } from "@/features/auth/hooks/useAuth";
import { cn } from "@/lib/utils";
import { useTheme } from "@/theme/ThemeProvider";
export function MainLayout(){const [open,setOpen]=useState(false);const [collapsed,setCollapsed]=useState(()=>localStorage.getItem("sidebar-collapsed")==="true");const {data:user}=useProfile();const {theme,setTheme}=useTheme();const logout=useLogout();const toggle=()=>{const value=!collapsed;setCollapsed(value);localStorage.setItem("sidebar-collapsed",String(value));};const items=visibleNavigation(user?.role);return <div className="min-h-screen bg-background text-foreground"><aside className={cn("fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r bg-card transition-transform md:translate-x-0",collapsed&&"md:w-16",open?"translate-x-0":"-translate-x-full")}><div className="flex h-16 items-center justify-between border-b px-4"><Link to="/" className="font-semibold">{collapsed?"PS":APP_NAME}</Link><Button aria-label="Collapse sidebar" variant="ghost" size="icon" onClick={toggle} className="hidden md:inline-flex"><Menu className="h-4 w-4"/></Button><Button aria-label="Close navigation" variant="ghost" size="icon" onClick={()=>setOpen(false)} className="md:hidden"><X className="h-4 w-4"/></Button></div><nav aria-label="Main navigation" className="flex-1 space-y-1 p-3">{items.map(({label,to,icon:Icon})=><NavLink key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>cn("flex items-center gap-3 rounded-md px-3 py-2 text-sm",isActive?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-accent hover:text-foreground")}><Icon className="h-4 w-4 shrink-0"/><span className={cn(collapsed&&"md:hidden")}>{label}</span></NavLink>)}</nav></aside>{open&&<button aria-label="Close overlay" className="fixed inset-0 z-30 bg-black/40 md:hidden" onClick={()=>setOpen(false)}/>}<div className={cn("min-h-screen transition-[margin] md:ml-64",collapsed&&"md:ml-16")}><header className="sticky top-0 z-20 flex h-16 items-center gap-3 border-b bg-background/95 px-4 backdrop-blur"><Button aria-label="Open navigation" variant="ghost" size="icon" onClick={()=>setOpen(true)} className="md:hidden"><Menu className="h-4 w-4"/></Button><div className="hidden max-w-md flex-1 items-center gap-2 rounded-md border px-3 py-1.5 text-sm text-muted-foreground sm:flex"><Search className="h-4 w-4"/>Global search</div><div className="ml-auto flex items-center gap-2"><Button variant="ghost" size="sm" onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?"Light":"Dark"}</Button><Link to="/profile"><Button variant="outline" size="sm">{user?.first_name??"Profile"}</Button></Link><Button variant="ghost" size="sm" onClick={()=>logout.mutate()} disabled={logout.isPending}>Log out</Button></div></header><main className="min-w-0"><Outlet/></main></div></div>}
