# Generated by Django 5.1.4 on 2026-07-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("families", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_family__e61372_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_househo_6ef6c2_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="family_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="household_id",
        ),
        migrations.AddField(
            model_name="user",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="families.family",
            ),
        ),
    ]
