# Generated by Django 5.1.4 on 2026-07-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_accounts_us_family__e61372_idx_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("families", "0001_initial"),
        ("households", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="households.household",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["family", "status"], name="accounts_us_family__e61372_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["household"], name="accounts_us_househo_6ef6c2_idx"),
        ),
    ]
