import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { api } from "@/api/axios";
import { Button } from "@/components/ui/button";
import { ErrorState, PageLoader } from "@/components/system/states";
import { useTheme } from "@/theme/ThemeProvider";
type Preference={in_app_enabled:boolean;email_enabled:boolean;push_enabled:boolean;muted_types:string[]};
export function SettingsPage(){const client=useQueryClient();const { theme, setTheme } = useTheme();const prefs=useQuery<Preference>({queryKey:["notification-preferences"],queryFn:()=>api.get("/notifications/preferences/").then(r=>r.data.data)});const save=useMutation({mutationFn:(data:Preference)=>api.post("/notifications/preferences/",data),onSuccess:()=>client.invalidateQueries({queryKey:["notification-preferences"]})});if(prefs.isLoading)return <PageLoader/>;if(prefs.isError)return <ErrorState message="Unable to load settings." retry={()=>prefs.refetch()}/>;const value=prefs.data;return <div className="mx-auto max-w-2xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Personal settings</h1><p className="text-sm text-muted-foreground">Notification preferences are saved to your account.</p></div><section className="space-y-4 rounded-lg border p-5"><h2 className="font-medium">Notifications</h2>{(["in_app_enabled","email_enabled","push_enabled"] as const).map(key=><label key={key} className="flex items-center justify-between gap-4"><span className="capitalize">{key.replaceAll("_"," ")}</span><input type="checkbox" checked={value?.[key]??false} onChange={e=>value&&save.mutate({...value,[key]:e.target.checked})}/></label>)}</section><section className="rounded-lg border p-5"><h2 className="font-medium">Theme</h2><div className="mt-3 flex gap-2"><Button variant={theme==="light"?"default":"outline"} onClick={()=>setTheme("light")}>Light</Button><Button variant={theme==="dark"?"default":"outline"} onClick={()=>setTheme("dark")}>Dark</Button></div></section></div>}

