# Generated by Django 5.1.4 on 2026-07-13 09:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.validators
import apps.members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        default=apps.members.models.generate_employee_code,
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("cousin", "Cousin"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a_positive", "A+"),
                            ("a_negative", "A-"),
                            ("b_positive", "B+"),
                            ("b_negative", "B-"),
                            ("ab_positive", "AB+"),
                            ("ab_negative", "AB-"),
                            ("o_positive", "O+"),
                            ("o_negative", "O-"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=15,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("joining_date", models.DateField(auto_now_add=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.members.models.member_photo_path
                    ),
                ),
                ("aadhaar_number_ready", models.BooleanField(default=False)),
                ("pan_number_ready", models.BooleanField(default=False)),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[apps.common.validators.validate_phone_number],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="families.family",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="households.household",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "members_member",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["family", "status"], name="members_mem_family__b3efd7_idx"
                    ),
                    models.Index(fields=["household"], name="members_mem_househo_1d6da4_idx"),
                    models.Index(fields=["relationship"], name="members_mem_relatio_677ddc_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "employee_code"), name="unique_employee_code_per_family"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MemberInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[apps.common.validators.validate_phone_number],
                    ),
                ),
                ("role", models.CharField(default="member", max_length=20)),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("cousin", "Cousin"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="families.family",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="households.household",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Invitation",
                "db_table": "members_invitation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["family", "status"], name="members_inv_family__7e8676_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email__isnull", False), ("mobile__isnull", False), _connector="OR"
                        ),
                        name="invitation_requires_email_or_mobile",
                    )
                ],
            },
        ),
    ]
