import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
 initial=True
 dependencies=[("families","0001_initial"),("households","0001_initial"),("members","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
 migrations.CreateModel(name="DocumentCategory",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("name",models.CharField(max_length=100)),("description",models.TextField(blank=True)),("icon",models.CharField(blank=True,max_length=50)),("color",models.CharField(default="#64748b",max_length=7)),("status",models.CharField(default="active",max_length=20)),("sort_order",models.PositiveIntegerField(default=0)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="document_categories",to="families.family"))],options={"db_table":"documents_category","ordering":["sort_order","name"]}),
 migrations.CreateModel(name="StorageUsage",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("bytes_used",models.PositiveBigIntegerField(default=0)),("document_count",models.PositiveIntegerField(default=0)),("updated_at",models.DateTimeField(auto_now=True)),("family",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="storage_usage",to="families.family"))],options={"db_table":"documents_storage_usage"}),
 migrations.CreateModel(name="Document",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("document_number",models.CharField(editable=False,max_length=30,unique=True)),("title",models.CharField(max_length=200)),("description",models.TextField(blank=True)),("reference_type",models.CharField(blank=True,max_length=30)),("reference_id",models.UUIDField(blank=True,null=True)),("storage_provider",models.CharField(default="local",max_length=20)),("original_filename",models.CharField(max_length=255)),("stored_filename",models.CharField(max_length=255)),("file",models.FileField(upload_to="private/documents")),("file_extension",models.CharField(max_length=15)),("mime_type",models.CharField(max_length=100)),("file_size",models.PositiveBigIntegerField()),("checksum",models.CharField(db_index=True,max_length=64)),("version",models.PositiveIntegerField(default=1)),("is_latest",models.BooleanField(default=True)),("visibility",models.CharField(default="family",max_length=20)),("status",models.CharField(default="active",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("is_deleted",models.BooleanField(db_index=True,default=False)),("category",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="documents",to="documents.documentcategory")),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="documents",to="families.family")),("household",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="documents",to="households.household")),("owner",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="owned_documents",to="members.member")),("uploaded_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="uploaded_documents",to=settings.AUTH_USER_MODEL))],options={"db_table":"documents_document","ordering":["-created_at"]}),
 migrations.CreateModel(name="DocumentVersion",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("version_number",models.PositiveIntegerField()),("stored_filename",models.CharField(max_length=255)),("file",models.FileField(upload_to="private/documents")),("checksum",models.CharField(max_length=64)),("created_at",models.DateTimeField(auto_now_add=True)),("remarks",models.TextField(blank=True)),("document",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="versions",to="documents.document")),("uploaded_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="document_versions",to=settings.AUTH_USER_MODEL))],options={"db_table":"documents_version","ordering":["-version_number"]}),
 migrations.CreateModel(name="DocumentShare",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("permission",models.CharField(default="read",max_length=20)),("expiry_date",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("document",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="shares",to="documents.document")),("shared_by",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="document_shares_made",to=settings.AUTH_USER_MODEL)),("shared_with",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="document_shares_received",to="members.member"))],options={"db_table":"documents_share"}),
 migrations.CreateModel(name="DocumentAccessLog",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("action",models.CharField(max_length=20)),("ip_address",models.GenericIPAddressField(blank=True,null=True)),("device",models.CharField(blank=True,max_length=255)),("browser",models.CharField(blank=True,max_length=255)),("created_at",models.DateTimeField(auto_now_add=True)),("document",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="access_logs",to="documents.document")),("member",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="document_access_logs",to="members.member"))],options={"db_table":"documents_access_log","ordering":["-created_at"]}),
 migrations.AddConstraint(model_name="documentcategory",constraint=models.UniqueConstraint(fields=("family","name"),name="document_category_per_family")),migrations.AddConstraint(model_name="documentversion",constraint=models.UniqueConstraint(fields=("document","version_number"),name="document_version_number")),migrations.AddConstraint(model_name="documentshare",constraint=models.UniqueConstraint(fields=("document","shared_with"),name="document_shared_once_per_member")),migrations.AddIndex(model_name="document",index=models.Index(fields=["family","category"],name="documents_d_family__d8e0ec_idx")),migrations.AddIndex(model_name="document",index=models.Index(fields=["family","reference_type","reference_id"],name="documents_d_family__9212e7_idx")),migrations.AddIndex(model_name="documentaccesslog",index=models.Index(fields=["document","action","-created_at"],name="documents_a_documen_73bf2d_idx"))]

