# Generated by Django 5.1.4 on 2026-09-22 13:44

from django.conf import settings
from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_family_scope"),
        ("families", "0001_initial"),
        ("households", "0002_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_family__d84e8f_idx",
            old_name="documents_d_family__d8e0ec_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_family__051926_idx",
            old_name="documents_d_family__9212e7_idx",
        ),
        migrations.RenameIndex(
            model_name="documentaccesslog",
            new_name="documents_a_documen_c960ef_idx",
            old_name="documents_a_documen_73bf2d_idx",
        ),
        migrations.AlterField(
            model_name="document",
            name="document_number",
            field=models.CharField(
                default=apps.documents.models.number, editable=False, max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=apps.documents.models.stored_path),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="file",
            field=models.FileField(upload_to=apps.documents.models.stored_path),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["household"], name="documents_d_househo_ff8e52_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["owner"], name="documents_d_owner_i_fa3cc1_idx"),
        ),
    ]
