import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [("families", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
      migrations.CreateModel(name="SavedReport", fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("name",models.CharField(max_length=150)),("report_type",models.CharField(max_length=30)),("filters",models.JSONField(blank=True,default=dict)),("is_shared",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="saved_reports",to="families.family")),("owner",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="saved_reports",to=settings.AUTH_USER_MODEL))],options={"db_table":"reports_saved_report","ordering":["-updated_at"]}),
      migrations.CreateModel(name="ReportSchedule", fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("report_type",models.CharField(max_length=30)),("filters",models.JSONField(blank=True,default=dict)),("frequency",models.CharField(choices=[("daily","Daily"),("weekly","Weekly"),("monthly","Monthly"),("yearly","Yearly")],max_length=12)),("recipients",models.JSONField(blank=True,default=list)),("is_active",models.BooleanField(default=True)),("last_run_at",models.DateTimeField(blank=True,null=True)),("next_run_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="report_schedules",to=settings.AUTH_USER_MODEL)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="report_schedules",to="families.family")),("saved_report",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="schedules",to="reports.savedreport"))],options={"db_table":"reports_schedule"}),
      migrations.CreateModel(name="ReportExportHistory",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("report_type",models.CharField(max_length=30)),("export_format",models.CharField(max_length=10)),("filters",models.JSONField(blank=True,default=dict)),("row_count",models.PositiveIntegerField(default=0)),("created_at",models.DateTimeField(auto_now_add=True)),("family",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="report_exports",to="families.family")),("user",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="report_exports",to=settings.AUTH_USER_MODEL))],options={"db_table":"reports_export_history","ordering":["-created_at"]}),
    ]
